name: Format Julia Code
on:
  push:
    branches: "*"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: domluna/JuliaFormatter-action@master
      with:
        args: -v .
      - name: lint
        run: echo "hi"