name: Format

on:
  push:
    branches:
      - 'master'
    tags: '*'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: domluna/JuliaFormatter-action@master
      with:
        args: -v .
